EliteEscapes/EliteEscapes.Web/Controllers/AmenityController.cs
using EliteEscapes.Application.Common.Interfaces;
using EliteEscapes.Application.Common.Utility;
using EliteEscapes.Application.Services.Interface;
using EliteEscapes.Domain.Entities;
using EliteEscapes.Infrastructure.Data;
using EliteEscapes.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace EliteEscapes.Web.Controllers
{
    [Authorize(Roles = SD.Role_Admin)]
    public class AmenityController : Controller
    {
        private readonly IAmenityService _amenityService;
        private readonly IVillaService _villaService;

        public AmenityController(IAmenityService amenityService, IVillaService villaService)
        {
            _amenityService = amenityService;
            _villaService = villaService;
        }
        public IActionResult Index()
        {
            var amenities = _amenityService.GetAllAmenities();
            return View(amenities);
        }
        public IActionResult Create()
        {
            AmenityVM amenityVM = new()
            {
                VillaList = _villaService.GetAllVillas().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                })
            };
            return View(amenityVM);
        }
        [HttpPost]
        public IActionResult Create(AmenityVM obj)
        {
          
            if (ModelState.IsValid )
            {
                _amenityService.CreateAmenity(obj.Amenity);
                TempData["success"] = "Amenity  Created Successfully";
                return RedirectToAction("Index");
            }

            obj.VillaList = _villaService.GetAllVillas().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });
            return View(obj);
        }

        public IActionResult Update(int amenityId)
        {
            AmenityVM amenityVM = new()
            {
                VillaList = _villaService.GetAllVillas().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),
                Amenity = _amenityService.GetAmenityById(amenityId)
            };
            if (amenityVM.Amenity == null)
            {
                return RedirectToAction("Error","Home");
            }
            return View(amenityVM);
        }

        [HttpPost]
        public IActionResult Update(AmenityVM amenityVM)
        {
            if (ModelState.IsValid)
            {
                _amenityService.UpdateAmenity(amenityVM.Amenity);
               
                TempData["success"] = "The Amenity has been updated Successfully";
                return RedirectToAction("Index");
            }
            amenityVM.VillaList = _villaService.GetAllVillas().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });
          
            return View(amenityVM);
        }

        public IActionResult Delete(int amenityId)
        {
            AmenityVM amenityVM = new()
            {
                VillaList = _villaService.GetAllVillas().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),
                Amenity = _amenityService.GetAmenityById(amenityId)
            };
            if (amenityVM.Amenity == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(amenityVM);
        }


        [HttpPost]
        public IActionResult Delete(AmenityVM amenityVM)
        {
           Amenity? objFromDb = _amenityService.GetAmenityById(amenityVM.Amenity.Id);
            if (objFromDb == null)
            {
                TempData["error"] = "Amenity could Not be Deleted Successfully";
                return RedirectToAction("Error", "Home");

            }
            _amenityService.DeleteAmenity(objFromDb.Id);          
            TempData["success"] = "Amenity Deleted Successfully";
            return RedirectToAction("Index");
        }
    }
}

EliteEscapes/EliteEscapes.Web/Controllers/BookingController.cs
using System.Security.Claims;
using EliteEscapes.Application.Common.Interfaces;
using EliteEscapes.Application.Common.Utility;
using EliteEscapes.Domain.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Stripe.Checkout;
using Syncfusion.DocIO.DLS;
using Syncfusion.DocIO;
using Syncfusion.DocIORenderer;
using Syncfusion.Drawing;
using Syncfusion.Pdf;
using EliteEscapes.Application.Services.Interface;
using Microsoft.AspNetCore.Identity;
using EliteEscapes.Application.Contract;

namespace EliteEscapes.Web.Controllers
{
    public class BookingController : Controller
    {
       
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IVillaService _villaService;
        private readonly IBookingService _bookingService;
        private readonly IVillaNumberService _villaNumberService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IPaymentService _paymentService;
        private readonly IEmailService _emailService;

        public BookingController(IWebHostEnvironment webHostEnvironment,IVillaService villaService,IBookingService bookingService,IVillaNumberService villaNumberService,UserManager<ApplicationUser> userManager,IPaymentService paymentService,IEmailService emailService)
        {
            
            _webHostEnvironment = webHostEnvironment;
            _villaService = villaService;
            _bookingService = bookingService;
            _villaNumberService = villaNumberService;
            _userManager = userManager;
            _paymentService = paymentService;
            _emailService = emailService;
        }

        [Authorize]
        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        public IActionResult FinalizeBooking(int villaId, string checkInDate, int nights)
        {

            var cliamIdentity = (ClaimsIdentity)User.Identity;
            var userId = cliamIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            ApplicationUser user = _userManager.FindByIdAsync(userId).GetAwaiter().GetResult();

            DateOnly parsedCheckInDate = DateOnly.ParseExact(checkInDate, "dd/MM/yyyy");


            Booking booking = new()
            {
                VillaId = villaId,
                CheckInDate = parsedCheckInDate,
                Nights = nights,
                CheckOutDate = parsedCheckInDate.AddDays(nights),
                Villa = _villaService.GetVillaById(villaId),
                UserId = userId,
                Phone = user.PhoneNumber,
                Email = user.Email,
                Name = user.Name
            };
            booking.TotalCost = booking.Villa.Price * nights;
            
            return View(booking);
        }

        [Authorize]
        [HttpPost]
        public IActionResult FinalizeBooking(Booking booking)
        {
            var villa = _villaService.GetVillaById(booking.VillaId);
            booking.CheckOutDate = booking.CheckInDate.AddDays(booking.Nights);
            booking.TotalCost = villa.Price * booking.Nights;
            booking.Status = SD.StatusPending;
            booking.BookingDate = DateTime.Now;

            if(!_villaService.IsVillaAvailableByDate(villa.Id,booking.Nights,booking.CheckInDate))
            {
                TempData["Error"] = " Rooms  Has Been Sold Out!";

                return RedirectToAction(nameof(FinalizeBooking), new 
                {
                    villaId = booking.VillaId,
                    checkInDate = booking.CheckInDate,
                    nights = booking.Nights 
                });
            }

            _bookingService.CreateBooking(booking);

            var domain = Request.Scheme + "://" + Request.Host.Value + "/";
            
            var options = _paymentService.CreateStripeSessionOptions(booking,villa,domain);

            var session = _paymentService.CreateStripeSession(options);
            _bookingService.UpdateStripePaymentID(booking.Id, session.Id, session.PaymentIntentId);
            

            Response.Headers.Add("Location", session.Url);
            return new StatusCodeResult(303);

        }

        [Authorize]
        [HttpPost]
        public IActionResult RetryPayment(int bookingId)
        {
            var booking = _bookingService.GetBookingById(bookingId);
            if (booking == null)
            {
                return NotFound("Booking not found.");
            }

            var villa = _villaService.GetVillaById(booking.VillaId);
            if (villa == null)
            {
                return NotFound("Villa not found.");
            }

            var domain = Request.Scheme + "://" + Request.Host.Value + "/";

            var options = _paymentService.CreateStripeSessionOptions(booking, villa, domain);

            var session = _paymentService.CreateStripeSession(options);

            // Update booking with new Stripe session details
            _bookingService.UpdateStripePaymentID(booking.Id, session.Id, session.PaymentIntentId);

            Response.Headers.Add("Location", session.Url);
            return new StatusCodeResult(303); // Redirect to Stripe Payment Gateway
        }


        [Authorize]
        public IActionResult BookingConfirmation(int bookingId)
        {
            Booking bookingFromDb = _bookingService.GetBookingById(bookingId);

            if (bookingFromDb.Status == SD.StatusPending)
            {
                //this is a pending order, we need to confirm if payment was successful

                var service = new SessionService();
                Session session = service.Get(bookingFromDb.StripeSessionId);

                if (session.PaymentStatus == "paid")
                {
                    _bookingService.UpdateStatus(bookingFromDb.Id, SD.StatusApproved,0);
                    _bookingService.UpdateStripePaymentID(bookingFromDb.Id, session.Id, session.PaymentIntentId);

                    // Generate Invoice PDF
                    byte[] pdfBytes = GenerateInvoicePDF(bookingFromDb);

                    // Send Email with Invoice
                    _emailService.SendEmailWithAttachmentAsync(
                        bookingFromDb.Email,
                        "Booking Confirmation - EliteEscapes",
                        "<p>Your booking has been confirmed. Please find the attached invoice.</p>",
                        pdfBytes,
                        "BookingInvoice.pdf"
                    );

                }
            }
            return View(bookingFromDb);
        }

        [HttpGet]
        [Authorize]
        public IActionResult GetAll(string status)
        {
            IEnumerable<Booking> objBookings;
            string userId = "";

            if (string.IsNullOrEmpty(status))
            {
                status = "";
            }
           if(!User.IsInRole(SD.Role_Admin))
            {
                var claimsIdentity =(ClaimsIdentity)User.Identity;
                userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
            }
           objBookings = _bookingService.GetAllBookings(userId, status);
           
            return Json(new { data = objBookings });
        }

        [Authorize]
        public IActionResult BookingDetails(int bookingId)
        {
            Booking bookingFromDb = _bookingService.GetBookingById(bookingId);

            if(bookingFromDb.VillaNumber==0 && bookingFromDb.Status == SD.StatusApproved)
            {
                var availableVillaNumber = AssignAvailableVillaNumberByVilla(bookingFromDb.VillaId);

                bookingFromDb.VillaNumbers = _villaNumberService.GetAllVillaNumbers().Where(u=>u.VillaId == bookingFromDb.VillaId && availableVillaNumber.Any(x=>x==u.Villa_Number)).ToList();
            }


            return View(bookingFromDb);
        }

        [HttpPost]
        [Authorize]
        public IActionResult GenerateInvoice(int id,string downloadType)
        {
            string basePath = _webHostEnvironment.WebRootPath;

            WordDocument document = new WordDocument();


            // Load the template.
            string dataPath = basePath + @"/exports/BookingDetails.docx";
            using FileStream fileStream = new(dataPath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
            document.Open(fileStream, FormatType.Automatic);

            //Update Template
            Booking bookingFromDb = _bookingService.GetBookingById(id);

            TextSelection textSelection = document.Find("xx_customer_name", false, true);
            WTextRange textRange = textSelection.GetAsOneRange();
            textRange.Text = bookingFromDb.Name;

            textSelection = document.Find("xx_customer_phone", false, true);
            textRange = textSelection.GetAsOneRange();
            textRange.Text = bookingFromDb.Phone;

            textSelection = document.Find("xx_customer_email", false, true);
            textRange = textSelection.GetAsOneRange();
            textRange.Text = bookingFromDb.Email;

            textSelection = document.Find("XX_BOOKING_NUMBER", false, true);
            textRange = textSelection.GetAsOneRange();
            textRange.Text = "BOOKING ID - " + bookingFromDb.Id;
            textSelection = document.Find("XX_BOOKING_DATE", false, true);
            textRange = textSelection.GetAsOneRange();
            textRange.Text = "BOOKING DATE - " + bookingFromDb.BookingDate.ToShortDateString();


            textSelection = document.Find("xx_payment_date", false, true);
            textRange = textSelection.GetAsOneRange();
            textRange.Text = bookingFromDb.PaymentDate.ToShortDateString();
            textSelection = document.Find("xx_checkin_date", false, true);
            textRange = textSelection.GetAsOneRange();
            textRange.Text = bookingFromDb.CheckInDate.ToShortDateString();

EliteEscapes/EliteEscapes.Web/Controllers/VillaController.cs
using EliteEscapes.Application.Common.Interfaces;
using EliteEscapes.Application.Services.Interface;
using EliteEscapes.Domain.Entities;
using EliteEscapes.Infrastructure.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EliteEscapes.Web.Controllers
{
    [Authorize]
    public class VillaController : Controller
    {
        private readonly IVillaService _villaService;

        public VillaController( IVillaService villaService)
        {
            _villaService = villaService;
        }
        public IActionResult Index()
        {
            var Villas = _villaService.GetAllVillas();
            return View(Villas);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Villa obj)
        {
            if (obj.Name == obj.Description)
            {
                ModelState.AddModelError("Description", "Name and Description cannot be the same");
            }
            if (ModelState.IsValid)
            {
                _villaService.CreateVilla(obj);
                TempData["success"] = "Villa Created Successfully";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Update(int villaId)
        {
            Villa? obj = _villaService.GetVillaById(villaId);
            if (obj == null)
            {
                return RedirectToAction("Error","Home");
            }
            return View(obj);
        }

        [HttpPost]
        public IActionResult Update(Villa obj)
        {
            if(ModelState.IsValid && obj.Id > 0)
            {
               _villaService.UpdateVilla(obj);
                TempData["success"] = "Villa Updated Successfully";
                return RedirectToAction("Index");
            }
          
            return View(obj);
        }

        public IActionResult Delete(int villaId)
        {
            Villa? obj = _villaService.GetVillaById(villaId);
            if (obj == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(obj);
        }

        [HttpPost]
        public IActionResult Delete(Villa obj)
        {
           bool deleted = _villaService.DeleteVilla(obj.Id);
            if(deleted)
            {

                TempData["success"] = "Villa Deleted Successfully";
                return RedirectToAction(nameof(Index));

            }
           else
            {
                TempData["error"] = "Failed To Delete The Villa";
            }
           return View();
        }
    }
}

EliteEscapes/EliteEscapes.Web/Views/Shared/_Layout.cshtml
@using EliteEscapes.Application.Common.Utility
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - EliteEscapes.Web</title>
	<link rel="icon" type="image/x-icon" href="~/images/favicon.png" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.1/css/bootstrap.min.css" integrity="sha512-Z/def5z5u2aR89OuzYcxmDJ0Bnd5V1cKqBEbvLOiUNWdg9PQeXVvXLI90SE4QOHGlfLqUnDNVAYyZi8UwUTmWQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
	<link rel="stylesheet" href="~/EliteEscapes.Web.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<link rel="stylesheet" href="~/css/spinner.css" />
	<link rel="stylesheet" href="//cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" />

</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  border-bottom box-shadow">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/resort.png" style="width:35px" /></a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>


						<li class="nav-item">
							<a class="nav-link" asp-controller="Booking" asp-action="Index">Manage Bookings</a>
						</li>

					</ul>

					<div class="p-2 border rounded">
						<div class="form-check form-switch" id="btnSwitch">
							<input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckDefault">
							<label class="form-check-label" for="flexSwitchCheckDefault">Mode</label>
						</div>
					</div>
					<partial name="_LoginPartial" />
				</div>
			</div>
		</nav>
	</header>
	<div class="">
		<main role="main">
			<div class="loading spinner" style="display:none;"></div>
			<partial name="_Notification" />
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container text-center">
			Made with <i class="bi bi-heart-fill "></i> by Fresil & Diya
		</div>
	</footer>

	<script type="text/javascript">
		// Function to apply the theme based on localStorage
		function applyTheme() {
			const savedTheme = localStorage.getItem("themeMode") || "dark"; // Default to dark mode
			document.documentElement.setAttribute('data-bs-theme', savedTheme);
			document.getElementById("flexSwitchCheckDefault").checked = (savedTheme === "light");
		}

		// Apply theme on page load
		applyTheme();

		// Toggle theme and save the choice in localStorage
		document.getElementById('btnSwitch').addEventListener('click', () => {
			let currentTheme = document.documentElement.getAttribute('data-bs-theme');
			let newTheme = (currentTheme === "dark") ? "light" : "dark";

			document.documentElement.setAttribute('data-bs-theme', newTheme);
			localStorage.setItem("themeMode", newTheme); // Save mode in localStorage

			// Update toggle switch state
			document.getElementById("flexSwitchCheckDefault").checked = (newTheme === "light");
		});
	</script>

	@* jquery-ajax-unobtrusive@3.2.6 *@
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.0.1/js/bootstrap.bundle.min.js" integrity="sha512-sH8JPhKJUeA9PWk3eOcOl8U+lfZTgtBXD41q6cO/slwxGHCxKcW45K4oPCUhHG7NMB4mbKEddVmPuTXtpbCbFA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<script src="//cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js" asp-append-version="true"></script>
	@* <script src="~/js/jquery.unobtrusive-ajax.min.js"></script> *@
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

EliteEscapes/EliteEscapes.Web/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EliteEscapes.Web</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.1/css/bootstrap.min.css" integrity="sha512-Z/def5z5u2aR89OuzYcxmDJ0Bnd5V1cKqBEbvLOiUNWdg9PQeXVvXLI90SE4QOHGlfLqUnDNVAYyZi8UwUTmWQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/EliteEscapes.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/spinner.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="~/css/apexcharts.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow">
            <div class="container-fluid d-flex justify-content-between">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/resort.png" style="width:35px" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
            <partial name="_LayoutPartialAdmin"/>
        </nav>
    </header>
    <div class="container-fluid">
        <div class="loading spinner" style="display:none;"></div>
        <div class="row">
            <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-dark sidebar collapse">
                <div class="position-static pt-3">
                    <ul class="navbar-nav">
                        <li>
                            <div class="text-muted small fw-bold text-uppercase px-3">
                                Menu
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">
                                <span class="me-2"><i class="bi bi-house-door"></i></span>
                                <span>Home</span>
                            </a>
                            <a class="nav-link" asp-controller="Dashboard" asp-action="Index">
                                <span class="me-2"><i class="bi bi-speedometer2"></i></span>
                                <span>Dashboard</span>
                            </a>
                        </li>
                        <li>
                            <div class="text-muted small fw-bold text-uppercase px-3 mt-2">
                                Content Management
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Villa" asp-action="Index">
                                <span class="me-2"><i class="bi bi-house-door"></i></span>
                                <span>Villa</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="VillaNumber" asp-action="Index">
                                <span class="me-2"><i class="bi bi-list-ol"></i></span>
                                <span>VillaNumber</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Amenity" asp-action="Index">
                                <span class="me-2"><i class="bi bi-building"></i></span>
                                <span>Amenity</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Booking" asp-action="Index" asp-route-status="@SD.StatusApproved">
                                <span class="me-2"><i class="bi bi-journal-plus"></i></span>
                                <span>Booking</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 w-100">
                    <partial name="_Notification" />
                    @RenderBody()
                </div>
            </main>
        </div>
    </div>

    <footer class="border-top footer bg-dark text-muted">
        <div class="container text-center">
            Made with <i class="bi bi-heart-fill"></i> by Fresil & Diya
        </div>
    </footer>
    @* jquery-ajax-unobtrusive@3.2.6 *@

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.0.1/js/bootstrap.bundle.min.js" integrity="sha512-sH8JPhKJUeA9PWk3eOcOl8U+lfZTgtBXD41q6cO/slwxGHCxKcW45K4oPCUhHG7NMB4mbKEddVmPuTXtpbCbFA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js" asp-append-version="true"></script>
    @*  <script src="~/js/jquery.unobtrusive-ajax.min.js"></script> *@
    <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

EliteEscapes/EliteEscapes.Web/Views/Shared/_LayoutPartialAdmin.cshtml
@using Microsoft.AspNetCore.Identity

 @inject SignInManager<ApplicationUser> SignInManager
 @inject UserManager<ApplicationUser> UserManager


<ul class="navbar-nav  d-none d-md-flex nav-login">
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
           data-bs-toggle="dropdown" aria-expanded="false">
            Hello @UserManager.GetUserName(User)
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="nav-link text-center" asp-controller="Account" asp-action="Logout">Logout</a>
        </ul>
    </li>
</ul>

EliteEscapes/EliteEscapes.Web/Views/Shared/_Notification.cshtml
@if (TempData["error"] != null)
{
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
	<script type="text/javascript">
		toastr.error('@TempData["error"]');
	</script>
}
@if (TempData["success"] != null)
{
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
	<script type="text/javascript">
		toastr.success('@TempData["success"]');
	</script>
}